version: '3'

services:
  image-storage:
    image: image-storage
    build: 
      context: ./src/image-storage
      dockerfile: Dockerfile-dev
    container_name: image-storage
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./src/image-storage/:/user/src/app
      # - ./src/image-storage/IMAGE_DB:./IMAGE_DB
      # - ./src/image-storage/ENCR_IMAGE_DB:./ENCR_IMAGE_DB
    restart: "no"

  mongo:
    image: mongo
    container_name: imongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./MDB:/data/db

  mongo-express:
    container_name: imongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL:"mongodb://imongo:27017"
    depends_on:
      - mongo
  
  image-manager:
    container_name: image-manager
    build: 
      context: ./src/image-manager
      dockerfile: Dockerfile-dev
    restart: "no"
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI:"mongodb://imongo:27017"
    volumes:
      - ./src/image-manager:/user/src/app
    depends_on:
      - mongo
  
    